version: '3.9'

services:
  scheduler_db:
    container_name: db_container
    image: mongo:5.0.3
    # restart: always
    ports:
      - 27018:27017
    volumes:
      - db_container:/data/db

  shift-scheduler:
    container_name: shift-scheduler
    build: .
    ports:
      - 3000:3000
      - 4080:4080
    depends_on:
      - scheduler_db

volumes:
  db_container: {}
